version: '3'
services:
  db:
    image: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Filip123!
      POSTGRES_DB: mapket
  app:
    image: myapp
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mapket
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Filip123!
    depends_on:
      - db